LABELS_DIR='/home/guest/data_ssd/bdd/seg/labels/train/'
IMGS_DIR='/home/guest/data_ssd/bdd/seg/images/train/'
N_CLASS=1
RANDOM_SEED=1
TRAIN_BATCH_SIZE=16
VAL_BATCH_SIZE=4
TEST_BATCH_SIZE=2
MAX_EPOCHS=16
GPUS=[0] # use id 1 gpu
CHECK_VAL_EVERY_N_EPOCHS=2
TARGET_CLASS_ID=13 # CAR
CENTER_CROP_SIZE=512
DEVICE='cuda:0'
SMP_ENCODER='resnet34'
EARLY_STOPPING_PATIENCE=50
SAMPLE=False
RESUME_FROM_CHECKPOINT='./checkpoints/epoch=1-step=629.ckpt'